const API='/api';
let allTickets=[], allClients=[], allAgents=[];
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function go(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$('#'+page).classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('#pageTitle').textContent=page==='new'?'New Ticket':page==='detail'?'Ticket Detail':page[0].toUpperCase()+page.slice(1);if(page==='tickets')renderTickets();if(page==='clients')renderClients();if(page==='agents')renderAgents();if(page==='reports')renderReports();}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>go(x.dataset.page));
$('#newTicket').onclick=()=>go('new');$('#newTicket2').onclick=()=>go('new');

async function api(path,opts={}){let r=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json();}
async function loadTickets(){try{[allTickets,allClients,allAgents]=await Promise.all([api('/tickets'),api('/clients'),api('/agents')]);renderDashboard();renderTickets();}catch(e){console.error(e);seedDemo();}}
function seedDemo(){allClients=[{id:1,firstName:'Avuyile',lastName:'Mto',email:'avuyile.mto@gmail.co.za',company:'TCM',department:'IT',active:true},{id:2,firstName:'Nomsa',lastName:'Dlamini',email:'nomsa@client.co.za',company:'ABC Ltd',department:'Finance',active:true}];allAgents=[{id:1,name:'Sipho Mbeki',email:'sipho@tcm.co.za',team:'Service Desk',availability:'ONLINE',activeTickets:6},{id:2,name:'Lerato Ndlovu',email:'lerato@tcm.co.za',team:'Network',availability:'ONLINE',activeTickets:4}];allTickets=[{id:1,ticketNumber:'TCM-1001',title:'Laptop cannot connect to Wi-Fi',description:'Office laptop loses connection.',client:{firstName:'Avuyile',lastName:'Mto',email:'avuyile.mto@gmail.co.za'},priority:'HIGH',category:'NETWORK',status:'IN_PROGRESS',assignedAgent:{name:'Sipho Mbeki'},slaDeadline:new Date(Date.now()+3600000).toISOString(),createdAt:new Date().toISOString(),comments:[{author:'Avuyile Mto',body:'Still having the issue.',createdAt:new Date().toISOString(),internal:false}]}];renderDashboard();renderTickets();}
function renderDashboard(){let c=allTickets.length,o=allTickets.filter(t=>t.status==='OPEN').length,p=allTickets.filter(t=>t.status==='IN_PROGRESS').length,r=allTickets.filter(t=>t.status==='RESOLVED').length;$('#kpis').innerHTML=[['Total tickets',c,'All requests'],['Open',o,'Awaiting assignment'],['In progress',p,'Being worked on'],['Resolved',r,'Ready to close']].map(x=>`<div class="kpi card"><span>${x[0]}</span><b>${x[1]}</b><small>${x[2]}</small></div>`).join('');$('#recentTickets').innerHTML=allTickets.slice(0,6).map(ticketHTML).join('')||'<div class="empty">No tickets found.</div>';let overdue=allTickets.filter(t=>t.slaDeadline&&new Date(t.slaDeadline)<new Date()&&t.status!=='CLOSED'&&t.status!=='RESOLVED').length;$('#slaBox').innerHTML=`<div class="sla-number">${overdue}</div><p>Tickets currently beyond SLA</p><div class="sla-bar"><span style="width:${Math.max(8,100-overdue*12)}%"></span></div><small>Monitor response and resolution targets</small>`;}
function ticketHTML(t){let client=t.client?`${esc(t.client.firstName)} ${esc(t.client.lastName)}`:'Unknown';return `<div class="ticket-row" onclick="openTicket(${t.id})"><div><b>${esc(t.ticketNumber)}</b><strong>${esc(t.title)}</strong><small>${client} · ${esc(t.category)}</small></div><div><span class="badge ${t.priority.toLowerCase()}">${esc(t.priority)}</span><span class="badge status">${esc(t.status.replaceAll('_',' '))}</span></div></div>`}
function renderTickets(){let q=($('#search')?.value||'').toLowerCase(),s=$('#status')?.value||'',p=$('#priority')?.value||'';let list=allTickets.filter(t=>(!q||JSON.stringify(t).toLowerCase().includes(q))&&(!s||t.status===s)&&(!p||t.priority===p));$('#ticketRows').innerHTML=list.map(t=>`<tr onclick="openTicket(${t.id})"><td><b>${esc(t.ticketNumber)}</b></td><td>${esc(t.title)}</td><td>${esc(t.client?.firstName||'')} ${esc(t.client?.lastName||'')}</td><td><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span></td><td><span class="badge status">${t.status.replaceAll('_',' ')}</span></td><td>${esc(t.assignedAgent?.name||'Unassigned')}</td><td>${t.slaDeadline?new Date(t.slaDeadline).toLocaleString():'—'}</td></tr>`).join('')||'<tr><td colspan="7" class="empty">No tickets match your filters.</td></tr>';}
function renderClients(){$('#clientRows').innerHTML=allClients.map(c=>`<tr><td><b>${esc(c.firstName)} ${esc(c.lastName)}</b></td><td>${esc(c.email)}</td><td>${esc(c.company||'')}</td><td>${esc(c.department||'')}</td><td><span class="badge status">${c.active?'ACTIVE':'INACTIVE'}</span></td></tr>`).join('')}
function renderAgents(){$('#agentGrid').innerHTML=allAgents.map(a=>`<div class="card agent"><div class="avatar big">${esc(a.name.split(' ').map(x=>x[0]).join(''))}</div><h3>${esc(a.name)}</h3><p>${esc(a.team||'Service Desk')}</p><span class="online">● ${esc(a.availability||'ONLINE')}</span><b>${a.activeTickets||0}</b><small>active tickets</small></div>`).join('')}
function renderReports(){let total=allTickets.length,urgent=allTickets.filter(x=>x.priority==='URGENT'||x.priority==='HIGH').length;$('#reportGrid').innerHTML=[['First response SLA',total?Math.round((total-Math.min(urgent,total))/total*100):100,'%'],['Resolution rate',total?Math.round(allTickets.filter(x=>x.status==='RESOLVED'||x.status==='CLOSED').length/total*100):0,'%'],['High priority share',total?Math.round(urgent/total*100):0,'%'],['Avg. open queue',allTickets.filter(x=>!['RESOLVED','CLOSED'].includes(x.status)).length,'tickets']].map(x=>`<div class="card report"><span>${x[0]}</span><b>${x[1]}${x[2]}</b><small>Current service desk metric</small></div>`).join('')}
async function openTicket(id){go('detail');let t=allTickets.find(x=>x.id===id);try{t=await api('/tickets/'+id)}catch{}$('#detailBox').innerHTML=`<div class="detail-head"><button class="link" onclick="go('tickets')">← Tickets</button><h2>${esc(t.ticketNumber)} · ${esc(t.title)}</h2><div><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span><span class="badge status">${t.status.replaceAll('_',' ')}</span></div></div><div class="timeline">${['OPEN','IN_PROGRESS','PENDING_CUSTOMER','RESOLVED','CLOSED'].map((x,i)=>`<div class="step ${['OPEN','IN_PROGRESS','PENDING_CUSTOMER','RESOLVED','CLOSED'].indexOf(t.status)>=i?'done':''}">${x.replaceAll('_',' ')}</div>`).join('')}</div><div class="detail-grid"><div class="card conversation"><h3>Conversation</h3>${(t.comments||[]).map(m=>`<div class="message ${m.internal?'internal':''}"><b>${esc(m.author||'Support')}</b><small>${new Date(m.createdAt).toLocaleString()}</small><p>${esc(m.body)}</p></div>`).join('')||'<p class="muted">No comments yet.</p>'}<form onsubmit="addComment(event,${t.id})"><textarea id="reply" required placeholder="Write a reply..."></textarea><button class="primary">Send reply</button></form></div><div class="card details"><h3>Ticket details</h3><p><b>Client</b><br>${esc(t.client?.firstName||'')} ${esc(t.client?.lastName||'')}<br>${esc(t.client?.email||'')}</p><p><b>Category</b><br>${esc(t.category)}</p><p><b>Assigned agent</b><br>${esc(t.assignedAgent?.name||'Unassigned')}</p><p><b>SLA deadline</b><br>${t.slaDeadline?new Date(t.slaDeadline).toLocaleString():'—'}</p><label>Status<select onchange="changeStatus(${t.id},this.value)">${['OPEN','IN_PROGRESS','PENDING_CUSTOMER','RESOLVED','CLOSED'].map(x=>`<option ${x===t.status?'selected':''}>${x}</option>`).join('')}</select></label></div></div>`}
async function addComment(e,id){e.preventDefault();try{await api('/tickets/'+id+'/comments',{method:'POST',body:JSON.stringify({author:'Client User',body:$('#reply').value,internal:false})})}catch{}openTicket(id)}
async function changeStatus(id,status){try{await api('/tickets/'+id+'/status',{method:'PATCH',body:JSON.stringify({status})})}catch{}loadTickets();openTicket(id)}
$('#ticketForm').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),body=Object.fromEntries(f.entries());try{await api('/tickets',{method:'POST',body:JSON.stringify(body)});alert('Ticket created successfully.');e.target.reset();await loadTickets();go('tickets')}catch(err){alert('Backend unavailable. Start the Java Spring Boot server, then submit again.')}};$('#search').oninput=renderTickets;$('#status').onchange=renderTickets;$('#priority').onchange=renderTickets;loadTickets();
